%YAML:1.0
# data

# camera intrinsics
# fr1
#camera.fx: 517.3
#camera.fy: 516.5
#camera.cx: 325.1
#camera.cy: 249.7

#define m_fx 615.733276
#define m_fy 615.733337
#define m_px 314.356658
#define m_py 238.919251

#realsense
camera.fx: 615.7
camera.fy: 615.7
camera.cx: 314.4
camera.cy: 238.9

#kinect
#camera.fx: 570.3
#camera.fy: 570.3
#camera.cx: 319.5
#camera.cy: 239.5

camera.depth_scale: 5

camera.dispara1: 0
camera.dispara2: 0
camera.dispara3: 0
camera.dispara4: 0

